[project]
name = "ga4-admin-api-demo"
version = "0.1.0"
description = "An Example dlt source for the Google Analytics 4 Admin API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["dlt[bigquery]>=1.5.0", "google-analytics-admin>=0.24.0"]
